package com.tecnocampus.backendtfg.domain;

public enum TypeActivity {
    RUNNING, WALKING, CYCLING, HIKING, CLIMBING, HIIT, CROSSFIT, SPINNING, YOGA, PILATES, DANCE, BOXING, KICKBOXING, RACKET, FOOTBALL, TRIATHLON,
    AEROBICS, BADMINTON, BASEBALL, BASKETBALL, BIKING, BIKING_STATIONARY, BOOT_CAMP, CALISTHENICS, CRICKET, DANCING, ELLIPTICAL, FENCING, FOOTBALL_AMERICAN,
    FRISBEE_DISC, GOLF, GUIDED_BREATHING, GYMNASTICS, HANDBALL, HIGH_INTENSITY_INTERVAL_TRAINING, ICE_HOCKEY, ICE_SKATING, MARTIAL_ARTS, PADDLING, PARAGLIDING,
    RACQUETBALL, ROCK_CLIMBING, ROLLER_HOCKEY, ROWING, ROWING_MACHINE, RUGBY, RUNNING_TREADMILL, SAILING, SCUBA_DIVING, SKATING, SKIING, SNOWBOARDING, SNOWSHOEING,
    SOCCER, SOFTBALL, SQUASH, STAIR_CLIMBING, STAIR_CLIMBING_MACHINE, STRENGTH_TRAINING, STRETCHING, SURFING, SWIMMING_OPEN_WATER, SWIMMING_POOL, TABLE_TENNIS,
    TENNIS, VOLLEYBALL, WATER_POLO, WEIGHTLIFTING, WHEELCHAIR
}
// e.g., tennis or basketball SURFING, SKATING, TRIATHLON, OTHER