import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  cardContainer: {
    width: '100%',
    backgroundColor: '#14142A',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginLeft: 10,
  },
  bottleWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
    justifyContent: 'space-around',
  },
  bottleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 10,
    backgroundColor: 'rgba(76, 110, 245, 0.1)',
  },
  metrics: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(30, 30, 60, 0.5)',
    minWidth: 150,
  },
  metricValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  metricLabel: {
    fontSize: 14,
    color: '#AAAAAA',
    marginTop: 4,
  },
  percentageContainer: {
    width: '100%',
    marginTop: 10,
    alignItems: 'center',
  },
  percentage: {
    fontSize: 18,
    fontWeight: '600',
    color: '#61dafb',
    marginBottom: 5,
  },
  progressIndicator: {
    height: 4,
    backgroundColor: '#61dafb',
    borderRadius: 2,
    alignSelf: 'flex-start',
  },
  customInputContainer: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 15,
  },
  customInput: {
    flex: 1,
    backgroundColor: 'rgba(30, 30, 60, 0.5)',
    borderRadius: 10,
    padding: 12,
    color: '#FFFFFF',
    fontSize: 16,
    marginRight: 10,
  },
  addButton: {
    backgroundColor: '#4c6ef5',
    borderRadius: 10,
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  presetButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  presetButton: {
    backgroundColor: 'rgba(76, 110, 245, 0.2)',
    borderRadius: 10,
    padding: 12,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  presetButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
});
