import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  header: {
    paddingTop: 40,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 5,
    backgroundColor: '#1a1a2e',
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  backButton: {
    padding: 8,
  },
  refreshButton: {
    padding: 8,
  },
  content: {
    padding: 16,
    paddingBottom: 80,
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    backgroundColor: '#1a1a2e',
    borderRadius: 25,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  activeTab: {
    backgroundColor: '#232342',
  },
  tabText: {
    color: '#cccccc',
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
  },
  activeTabText: {
    color: '#61dafb',
    fontWeight: 'bold',
  },
  periodSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    marginTop: 8,
  },
  periodButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginHorizontal: 6,
    borderRadius: 20,
    backgroundColor: '#1a1a2e',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  activePeriod: {
    backgroundColor: '#4c6ef5',
  },
  periodText: {
    color: '#cccccc',
    fontSize: 14,
    fontWeight: '500',
  },
  activePeriodText: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  summaryCard: {
    marginBottom: 20,
  },
  summaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    padding: 20,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(97, 218, 251, 0.15)',
  },
  summaryItem: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 5,
  },
  summaryIcon: {
    marginBottom: 8,
    padding: 10,
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryValue: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#cccccc',
    marginTop: 4,
  },
  chart: {
    marginVertical: 10,
    borderRadius: 12,
    alignSelf: 'center',
    overflow: 'hidden',
    width: '100%',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    paddingBottom: 10,
    backgroundColor: '#1e1e38',
  },
  chartConfig: {
    backgroundColor: '#1a1a2e',
    backgroundGradientFrom: '#1a1a2e',
    backgroundGradientTo: '#1e1e38',
    decimalPlaces: 0,
    color: (opacity = 1) => `rgba(97, 218, 251, ${opacity})`,
    labelColor: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
    style: {
      borderRadius: 16,
      paddingRight: 15,
      paddingLeft: 10,
      paddingTop: 5,
      paddingBottom: 10,
    },
    propsForDots: {
      r: '6',
      strokeWidth: '2',
      stroke: '#61dafb',
      fill: '#1e1e38',
    },
    propsForBackgroundLines: {
      strokeDasharray: '',
      strokeWidth: 1,
      stroke: 'rgba(255, 255, 255, 0.1)',
    },
    propsForLabels: {
      fontSize: 10,
      fontWeight: 'bold',
      fill: '#ffffff',
    },
    horizontalLabelRotation: 0,
    horizontalOffset: 0,
    xLabelsOffset: 0,
    yLabelsOffset: 8,
    formatYLabel: (value) => value,
    formatXLabel: (value) => value,
    segments: 5,
  },
  scrollableChartContainer: {
    marginBottom: 5,
    borderRadius: 12,
    backgroundColor: '#1e1e38',
    padding: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  cardIcon: {
    marginRight: 10,
    padding: 8,
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitText: {
    fontSize: 12,
    color: '#cccccc',
    marginLeft: 5,
  },
  card: {
    marginBottom: 20,
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    padding: 20,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(97, 218, 251, 0.15)',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 5,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  errorText: {
    color: '#ff6b6b',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  // Añadir estos estilos al objeto StyleSheet.create
  noDataContainer: {
  alignItems: 'center',
  justifyContent: 'center',
  padding: 40,
  backgroundColor: '#1a1a2e',
  borderRadius: 16,
  marginVertical: 10,
  },
  noDataText: {
  color: '#cccccc',
  marginTop: 10,
  fontSize: 16,
  },
  chartHeader: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 15,
  paddingTop: 15,
  paddingBottom: 5,
  },
  chartTitle: {
  color: '#ffffff',
  fontSize: 16,
  fontWeight: 'bold',
  marginLeft: 10,
  },
  refreshButton: {
    backgroundColor: '#4c6ef5',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 15,
  },
  refreshButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Nuevos estilos para iconos con colores
  activityIconContainer: {
    backgroundColor: 'rgba(74, 105, 189, 0.2)',
  },
  sleepIconContainer: {
    backgroundColor: 'rgba(106, 90, 205, 0.2)',
  },
  stepsIconContainer: {
    backgroundColor: 'rgba(46, 204, 113, 0.2)',
  },
  timeIconContainer: {
    backgroundColor: 'rgba(52, 152, 219, 0.2)',
  },
  trendIconContainer: {
    backgroundColor: 'rgba(231, 76, 60, 0.2)',
  },
  trophyIconContainer: {
    backgroundColor: 'rgba(241, 196, 15, 0.2)',
  },
  starIconContainer: {
    backgroundColor: 'rgba(155, 89, 182, 0.2)',
  },
  calendarIconContainer: {
    backgroundColor: 'rgba(230, 126, 34, 0.2)',
  },
  // Estilos para los iconos de hidratación
  waterIconContainer: {
  backgroundColor: 'rgba(97, 218, 251, 0.15)',
  borderRadius: 30,
  padding: 10,
  width: 40,
  height: 40,
  justifyContent: 'center',
  alignItems: 'center',
  },
  percentIconContainer: {
  backgroundColor: 'rgba(76, 217, 100, 0.15)',
  borderRadius: 30,
  padding: 10,
  width: 40,
  height: 40,
  justifyContent: 'center',
  alignItems: 'center',
  },
  streakIconContainer: {
  backgroundColor: 'rgba(241, 196, 15, 0.15)',
  borderRadius: 30,
  padding: 10,
  width: 40,
  height: 40,
  justifyContent: 'center',
  alignItems: 'center',
  },
  
  // Nuevos estilos para etapas de sueño
  sleepStagesIconContainer: {
  backgroundColor: 'rgba(163, 161, 251, 0.15)',
  borderRadius: 30,
  padding: 10,
  width: 40,
  height: 40,
  justifyContent: 'center',
  alignItems: 'center',
  },
  stagesSummaryContainer: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  justifyContent: 'space-between',
  marginBottom: 15,
  marginTop: 5,
  },
  stageSummaryItem: {
  width: '48%',
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#232342',
  borderRadius: 8,
  padding: 10,
  marginBottom: 10,
  },
  stageColorIndicator: {
  width: 12,
  height: 12,
  borderRadius: 6,
  marginRight: 8,
  },
  stageName: {
  color: '#ffffff',
  fontSize: 14,
  fontWeight: '500',
  flex: 1,
  },
  stageValue: {
  color: '#ffffff',
  fontSize: 16,
  fontWeight: 'bold',
  },
  stageUnit: {
  color: '#aaaaaa',
  fontSize: 12,
  },
  chartDescription: {
  color: '#aaaaaa',
  fontSize: 12,
  marginTop: 10,
  lineHeight: 18,
  textAlign: 'center',
  paddingHorizontal: 10,
  },
  // Estilos para el header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 50, // Aumentamos el padding superior para más espacio
    backgroundColor: '#1a1a2e',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
  },
  backButton: {
    padding: 8,
  },
  headerRefreshButton: {
    padding: 8,
    backgroundColor: '#4c6ef5',
    borderRadius: 25,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: '#cccccc',
    fontSize: 16,
  },
  errorCard: {
    padding: 20,
    marginVertical: 20,
    backgroundColor: 'rgba(231, 76, 60, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(231, 76, 60, 0.3)',
  },
  remContainer: {
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    padding: 15,
    marginTop: 15,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(97, 218, 251, 0.15)',
  },
  remHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  remTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    marginLeft: 10,
  },
  remValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#6a5acd',
    marginVertical: 5,
  },
  remDescription: {
    display: 'none', // Ocultamos la descripción
  },
  remIconContainer: {
    backgroundColor: 'rgba(106, 90, 205, 0.2)',
    padding: 8,
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Estilos para el header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 50, // Aumentamos el padding superior para más espacio
    backgroundColor: '#1a1a2e',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
  },
  backButton: {
    padding: 8,
  },
  headerRefreshButton: {
    padding: 8,
    backgroundColor: '#4c6ef5',
    borderRadius: 25,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: '#cccccc',
    fontSize: 16,
  },
  errorCard: {
    padding: 20,
    marginVertical: 20,
    backgroundColor: 'rgba(231, 76, 60, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(231, 76, 60, 0.3)',
  },

  stagesSummaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  stageSummaryItem: {
    alignItems: 'center',
    flex: 1,
  },
  stagesContainer: {
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  stageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  stageIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginBottom: 5,
  },
  stageLabel: {
    color: '#ffffff',
    fontSize: 14,
    flex: 1,
  },
  stageValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },

  summaryCard: {
    backgroundColor: '#1e1e2e',
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
  },
  summaryContainer: {
    width: '100%',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  summaryItem: {
    alignItems: 'center',
    flex: 1,
  },
  summaryIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    marginVertical: 2,
  },
  summaryLabel: {
    fontSize: 12,
    color: '#aaaaaa',
  },
});
